In [28]:
import pandas as pd 
pd.set_option('display.max_columns', 21)
arquivo = pd.read_csv(r'/Users/gustavohenriquebonatopiresdemoraes/ia-portfolio-gustavo/exercicios/modulo1/kc_house_data.csv')
arquivo.head(15)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
10,1736800520,20150403T000000,662500.0,3,2.50,3560,9796,1.0,0,0,3,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
11,9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,4,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
12,114101516,20140528T000000,310000.0,3,1.00,1430,19901,1.5,0,0,4,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
13,6054650070,20141007T000000,400000.0,3,1.75,1370,9680,1.0,0,0,4,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,1175000570,20150312T000000,530000.0,5,2.00,1810,4850,1.5,0,0,3,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850

In [29]:
delete_columns = ['id', 'date', 'zipcode', 'lat', 'long']
arquivo.drop(columns = delete_columns, inplace= True)
arquivo.shape

(21613, 16)

In [30]:
y = arquivo['price']
x = arquivo.drop('price', axis = 1)

In [31]:
# A regressão linear é uma técnica estatística e de machine learning que modela a relação entre uma variável dependente 
#(a que queremos prever) e uma ou mais variáveis independentes (as que usamos para prever) como uma equação linear

from sklearn.linear_model import LinearRegression
modelo = LinearRegression()

In [32]:
from sklearn.model_selection import train_test_split
x_teste, x_treino, y_teste, y_treino = train_test_split(x, y, test_size = 0.30, random_state = 14)

In [33]:
modelo.fit(x_treino, y_treino)
resultado = modelo.score(x_teste, y_teste)
print(resultado)

0.6496316515239353

In [46]:
# Regularização L2 (Ridge) A Regressão Ridge é uma técnica estatística usada para corrigir o overfitting (sobreajuste) em modelos de machine learning
#e regressão linear, especialmente em casos de multicolinearidade (alta correlação entre variáveis)

from sklearn.linear_model import Ridge
# é padrão o alpha = 1
modeloRidge = Ridge(alpha=1)
modeloRidge.fit(x_treino, y_treino)
resultadoRidge = modeloRidge.score(x_teste, y_teste)
print(resultadoRidge)

0.6494811958649257

In [50]:
#Regularização L1 (Lasso) zera coeficientes – seleciona variáveis.
from sklearn.linear_model import Lasso
modeloLasso = Lasso(alpha = 30, max_iter = 50000, tol= 0.1)
modeloLasso.fit(x_treino, y_treino)
resultadoLasso = modeloLasso.score(x_teste, y_teste)
print(resultadoLasso)

0.6495722205193066

In [95]:
#Elastic Net Regression é um algoritmo de machine learning supervisionado que combina as técnicas de regularização Lasso (L1) e Ridge (L2) 
#para realizar regressão
from sklearn.linear_model import ElasticNet
modeloElastic = ElasticNet(alpha = 0.5, l1_ratio = 0.5, tol = 0.3)
modeloElastic.fit(x_treino, y_treino)
resultadoElastic = modeloElastic.score(x_teste, y_teste)
print(resultadoElastic)

0.6215748479957202